rust_arch:
  - x86_64-unknown-linux-gnu       # [linux64]
  - s390x-unknown-linux-gnu        # [s390x]
  - aarch64-unknown-linux-gnu      # [aarch64]
  - x86_64-apple-darwin            # [osx and x86_64]
  - aarch64-apple-darwin           # [osx and arm64]
rust_std_extra:
  - wasm32-wasip1
  - wasm32-wasip2
macos_min_version:
  - 10.12 # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:
  - 10.12 # [osx and x86_64]
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.12.sdk        # [osx and x86_64]