# !! update of rust version should be carried out together with rust-activation version update !!
# https://github.com/AnacondaRecipes/rust-activation-feedstock
{% set date = "2025-10-13" %}
{% set version = "1.92.0_" ~ date.replace('-', '_') %}

package:
  name: rust-nightly
  version: {{ version }}

source:
    #### start of main rust toolchain sources
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-x86_64-unknown-linux-gnu.tar.gz  # [linux64]
    sha256: c24621daf2ef3dbeffc20e83a707db0a1b82e47d51daa68d15b9439f82020b3f  # [linux64]
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-aarch64-unknown-linux-gnu.tar.gz  # [aarch64]
    sha256: 26b1868b33992a3f29477f760464c8659c5f244a6c6b280e9b6554f3830a5708  # [aarch64]
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-aarch64-apple-darwin.tar.gz  # [osx and arm64]
    sha256: fa81cfedc09622cae2f223364fc81f514f1189549df10c084e5450b9ded59288  # [osx and arm64]
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-x86_64-pc-windows-msvc.tar.gz  # [win]
    sha256: 4fa2a95764b99d818393d60c5934d4b7fc5cf23fa42b54961689942bc6f49992  # [win]
    folder: msvc  # [win]
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-x86_64-pc-windows-gnu.tar.gz  # [win64]
    sha256: dffc2146fa53fbc99badbcd915752c740d93f96da0c60ca39d26e4e96d996903  # [win64]
    folder: gnu  # [win]
    #### end of main rust toolchain sources
    #### start of rust-std-extra toolchain sources
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-std-nightly-wasm32-wasip1.tar.gz
    sha256: 1e9628057af8bbaf3d2e90a7b93aa309ce8b7fec0ef61cc9b007323fcbe64a93
    folder: rust-std-wasm32-wasip1
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-std-nightly-wasm32-wasip2.tar.gz
    sha256: ff93bb727960c12a8588cee9a4e4a70df4aec79be4512b9e8f6f1ac1590a6c76
    folder: rust-std-wasm32-wasip2
    #### end of rust-std-extra toolchain sources

build:
  number: 0

outputs:
  - name: rust-nightly
    script: install-msvc.bat  # [win]
    script: install-unix.sh  # [not win]
    build:
      # The distributed binaries are already relocatable
      binary_relocation: False
      runpath_whitelist:
        - $ORIGIN/../lib
      missing_dso_whitelist:
        - /usr/lib/libresolv.9.dylib
        - /usr/lib/libc++.1.dylib
        - /usr/lib/libc++abi.dylib
        - /usr/lib/libiconv.2.dylib
        - /usr/lib/libcurl.4.dylib
        - /usr/lib/libxar.1.dylib
        - $RPATH/libLLVM-14-rust-1.64.0-stable.so
        # Since 1.32.0 macOS also needs:
        - /System/Library/Frameworks/Python.framework/Versions/2.7/Python
        - /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
        - /usr/lib/libcompression.dylib
        - /usr/lib/libedit.3.dylib
        - /usr/lib/libform.5.4.dylib
        - /usr/lib/libncurses.5.4.dylib
        - /usr/lib/libpanel.5.4.dylib
        - /usr/lib/libxml2.2.dylib
        # Fixed via install_name_tool now (just declaring it here meant the thing using -
        # lib/rustlib/x86_64-apple-darwin/lib/python2.7/site-packages/lldb/lldb-argdumper - was
        # still unable to find it at runtime).
        # - $RPATH/libLLVM.dylib

        - '**/ld-linux-x86-64.so.2'
        - '**/libc.so.6'
        - '**/libdl.so.2'
        - '**/ld64.so.*'
        - '**/libgcc_s.so.1'
        - '**/libm.so.6'
        - '**/libpthread.so.0'
        - '**/librt.so.1'
        - '**/libgcc_s.so.1'
        - '**/libz.so.1'
        # Since 1.32.0 linux also needs:
        - '**/libstdc++.so.6'
        - '*/api-ms-win-core-winrt-l1-1-0.dll'  # [win]
        - '*/api-ms-win-core-winrt-error-l1-1-0.dll'  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}    # [osx]
        - {{ compiler('c') }}    # [osx]
        - posix  # [win]
    test:
      requires:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      files:
        - forge_test.sh  # [not win]
      commands:
        - if exist %LIBRARY_PREFIX%\share\doc\rust\html\sysroot exit 1  # [win]
        - rustc --version
        - cargo --help
        - rustc --help
        - rustdoc --help
        - time bash ./forge_test.sh  # [not win]

  - name: rust-gnu-nightly  # [win]
    script: install-gnu.bat  # [win]
    build:  # [win]
      # the distributed binaries are already relocatable
      binary_relocation: False  # [win]
      missing_dso_whitelist:  # [win]
        - '*/api-ms-win-core-winrt-l1-1-0.dll'  # [win]
        - '*/api-ms-win-core-winrt-error-l1-1-0.dll'  # [win]
    requirements:  # [win]
      build:  # [win]
        - posix # [win]
    test:  # [win]
      commands:  # [win]
        - rustc --version  # [win]
        - cargo --help  # [win]
        - rustc --help  # [win]
        - rustdoc --help  # [win]
        - if exist %LIBRARY_PREFIX%\share\doc\rust\html\sysroot exit 1  # [win]

  - name: rust-std-{{ rust_std_extra }}-nightly
    build:
      binary_relocation: False
      runpath_whitelist:
        - $ORIGIN/../lib
      missing_dso_whitelist:
        - "/lib64/libgcc_s.so.*"
        - "/lib64/librt.so.*"
        - "/lib64/libpthread.so.*"
        - "/lib64/libdl.so.*"
        - "/lib64/libc.so.*"
        - "/lib64/ld-linux-x86-64.so.*"  # [linux and x86_64]
      run_exports:
        strong:
          - {{ pin_subpackage("rust-nightly", exact=True) }}
    script: install-rust-std-extra.sh  # [unix]
    script: install-rust-std-extra.bat  # [win]
    requirements:
      build:
        - posix  # [win]
    test:
      commands:
        - echo ON  # [win]
        - test -f $PREFIX/lib/rustlib/{{ rust_std_extra }}/lib/libcore*.rlib  # [unix]
        # Make sure that the outputs do not clobber with other rust components
        - test -f $PREFIX/lib/rustlib/{{ rust_std_extra }}/lib/self-contained/libc.a  # [unix]
        - rustc --print target-list | grep {{ rust_std_extra }}  # [unix]
      requires:
        - {{ pin_subpackage('rust-nightly', exact=True) }}  # [unix]

about:
  home: https://www.rust-lang.org
  license: MIT AND Apache-2.0
  license_family: OTHER
  license_url: https://github.com/rust-lang/rust/blob/{{ version }}/COPYRIGHT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
  description: |
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://github.com/rust-lang/rust
  doc_url: https://www.rust-lang.org/learn

extra:
  # The license files cannot be found properly on Windows
  skip-lints:
    - missing_license_file
  recipe-maintainers:
    - abhi18av
    - dlaehnemann
    - johanneskoester
    - pkgw
    - katietz