{% set version = "1.79.0.dev20240328" %}
{% set version_main = version[:-12] %}
{% set nightly_date = version[10:14]+"-"+version[14:16]+"-"+version[16:18] %}

package:
  name: 'rust-suite'
  version: {{ version }}

# skipping s390x because nightly rust is only necessary for specific customer packages
source:
  - url: https://static.rust-lang.org/dist/{{ nightly_date }}/rust-nightly-x86_64-unknown-linux-gnu.tar.gz  # [linux and x86_64]
    sha256: 301318d082fcbed0dae5c71baeaf5634bcd646da9585d33544b3fb0e7beb04d7                                # [linux and x86_64]
  - url: https://static.rust-lang.org/dist/{{ nightly_date }}/rust-nightly-aarch64-unknown-linux-gnu.tar.gz  # [linux and aarch64]
    sha256: 2f856592ab8ebaae5d574d0ba522bc2bf8c10b494e201a40cacbae29787ec8d1                                 # [linux and aarch64]
  - url: https://static.rust-lang.org/dist/{{ nightly_date }}/rust-nightly-x86_64-apple-darwin.tar.gz  # [osx and x86_64]
    sha256: 196f0f668e092eee0b9251df2e6c8d94edb9575c2342247a934142dffdfb64fb                           # [osx and x86_64]
  - url: https://static.rust-lang.org/dist/{{ nightly_date }}/rust-nightly-aarch64-apple-darwin.tar.gz  # [osx and arm64]
    sha256: 9a991332b37dd05cb76d2455c5e945b0a0efdad54478a61f9d55b062736cbd13                            # [osx and arm64]
  - url: https://static.rust-lang.org/dist/{{ nightly_date }}/rust-nightly-x86_64-pc-windows-msvc.tar.gz  # [win]
    sha256: aa4f84009d29f47ad49b404dced55747ab4d8dd74ac18510c012707521f521b8                              # [win]
    folder: msvc                                                                                          # [win]
  - url: https://static.rust-lang.org/dist/{{ nightly_date }}/rust-nightly-x86_64-pc-windows-gnu.tar.gz  # [win]
    sha256: c5172107f02762fb264c9adb75d43fc537f4750d4af8dea7b6aa022f6c548173                             # [win]
    folder: gnu                                                                                          # [win]

build:
  skip: True  # [s390x]
  number: 0

outputs:
  - name: rust
    script: install-msvc.bat  # [win]
    script: install-unix.sh  # [not win]
    build:
      run_exports: # [osx and x86_64]
        strong_constrains: # [osx and x86_64]
          - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.12") }}  # [osx and x86_64]
      # the distributed binaries are already relocatable
      binary_relocation: False
      runpath_whitelist:
        - $ORIGIN/../lib
      missing_dso_whitelist:
        - '**/ld-linux-x86-64.so.2'        # [linux]
        - '**/libc.so.6'                   # [linux]
        - '**/libdl.so.2'                  # [linux]
        - '**/ld64.so.*'                   # [linux]
        - '**/libm.so.6'                   # [linux]
        - '**/libpthread.so.0'             # [linux]
        - '**/librt.so.1'                  # [linux]
        - '**/libgcc_s.so.1'               # [linux]
        - '**/libz.so.1'                   # [linux]
    requirements:
      build:
        - {{ compiler('c') }}    # [osx]
        - posix  # [win]
    test:
      requires:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      files:
        - forge_test.sh  # [not win]
      commands:
        - if exist %LIBRARY_PREFIX%\share\doc\rust\html\sysroot exit 1  # [win]
        - rustc --version
        - cargo --help
        - rustc --help
        - rustdoc --help
        - time bash ./forge_test.sh  # [not win]

  - name: rust-gnu  # [win]
    script: install-gnu.bat  # [win]
    build:  # [win]
      # the distributed binaries are already relocatable
      binary_relocation: False  # [win]
    requirements:  # [win]
      build:  # [win]
        - posix # [win]
    test:  # [win]
      commands:  # [win]
        - rustc --version  # [win]
        - cargo --help  # [win]
        - rustc --help  # [win]
        - rustdoc --help  # [win]
        - if exist %LIBRARY_PREFIX%\share\doc\rust\html\sysroot exit 1  # [win]

about:
  home: https://www.rust-lang.org
  license: MIT AND Apache-2.0
  license_family: OTHER
  license_url: https://github.com/rust-lang/rust/blob/{{ version_main }}/COPYRIGHT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
  description: |
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://github.com/rust-lang/rust
  doc_url: https://www.rust-lang.org/learn

extra:
  # The license files cannot be found properly on Windows
  skip-lints:
    - missing_license_file
  recipe-maintainers:
    - abhi18av
    - dlaehnemann
    - johanneskoester
    - pkgw
    - katietz
