{% set version = "1.82.0" %}

package:
  name: 'rust-suite'
  version: {{ version }}

source:
    #### start of main rust toolchain sources
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-unknown-linux-gnu.tar.gz  # [linux64]
    sha256: 0265c08ae997c4de965048a244605fb1f24a600bbe35047b811c638b8fcf676b  # [linux64]
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-aarch64-unknown-linux-gnu.tar.gz  # [aarch64]
    sha256: d7db04fce65b5f73282941f3f1df5893be9810af17eb7c65b2e614461fe31a48  # [aarch64]
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-s390x-unknown-linux-gnu.tar.gz  # [s390x]
    sha256: 63760886a9b2de6cb38f75a236db358939d904e205e1e2bc9d96cec69e00ae83  # [s390x]
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-apple-darwin.tar.gz  # [osx and x86_64]
    sha256: b1a289cabc523f259f65116a41374ac159d72fbbf6c373bd5e545c8e835ceb6a  # [osx and x86_64]
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-aarch64-apple-darwin.tar.gz  # [osx and arm64]
    sha256: 49b6d36b308addcfd21ae56c94957688338ba7b8985bff57fc626c8e1b32f62c  # [osx and arm64]
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-pc-windows-msvc.tar.gz  # [win]
    sha256: b5fac89899343fbc1b8438ff87b77cddaed90a75873db7b01f2c197a26ec9d52  # [win]
    folder: msvc  # [win]
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-pc-windows-gnu.tar.gz  # [win64]
    sha256: 23149a74246f2a50b6ff5d5c2ec3a1a65634bc207ab1267427e9c7ad6830374d  # [win64]
    folder: gnu  # [win]
    #### end of main rust toolchain sources
    #### start of rust-std toolchain sources
  - url: https://static.rust-lang.org/dist/rust-std-{{ version }}-x86_64-unknown-linux-gnu.tar.gz  # [linux and x86_64]
    sha256: e7e808b8745298369fa3bbc3c0b7af9ca0fb995661bd684a7022d14bc9ae0057  # [linux and x86_64]
    folder: rust-std  # [linux and x86_64]
  - url: https://static.rust-lang.org/dist/rust-std-{{ version }}-aarch64-unknown-linux-gnu.tar.gz  # [linux and aarch64]
    sha256: 82b2308ee531775bf4d1faa57bddfae85f363bec43ca36ba6db4ebad7c1450d4  # [linux and aarch64]
    folder: rust-std  # [linux and aarch64]
  - url: https://static.rust-lang.org/dist/rust-std-{{ version }}-x86_64-apple-darwin.tar.gz  # [osx and x86_64]
    sha256: 52084c8cdb34ca139a00f9f03f1a582d96b677e9f223a8d1aa31ae575a06cc16  # [osx and x86_64]
    folder: rust-std  # [osx and x86_64]
  - url: https://static.rust-lang.org/dist/rust-std-{{ version }}-aarch64-apple-darwin.tar.gz  # [osx and arm64]
    sha256: 5ec28e75ed8715efaa2490d76ae026a34b13df6899d98b14d0a6995556f4e6b4  # [osx and arm64]
    folder: rust-std  # [osx and arm64]
  - url: https://static.rust-lang.org/dist/rust-std-{{ version }}-x86_64-pc-windows-msvc.tar.gz  # [win]
    sha256: afe8fbf37001f559cbddc7c786db50946d3f483f12a290115ee1ef8fff10a833  # [win]
    folder: rust-std  # [win]
    #### end of rust-std toolchain sources
    #### start of rust-std-extra toolchain sources
  - url: https://static.rust-lang.org/dist/rust-std-{{ version }}-wasm32-wasip1.tar.gz
    sha256: 41cce791e0b2e27838f9ef09707605bb2d4571293fc0e157cd260a0adc90a628
    folder: rust-std-wasm32-wasip1
  - url: https://static.rust-lang.org/dist/rust-std-{{ version }}-wasm32-wasip2.tar.gz
    sha256: 5ee71ee1909e1bd960977b3f2c0bc25e77aae5c447bbc6802a19495f7f30538f
    folder: rust-std-wasm32-wasip2
    #### end of rust-std-extra toolchain sources

build:
  number: 0

outputs:
  - name: rust
    script: install-msvc.bat  # [win]
    script: install-unix.sh  # [not win]
    build:
      run_exports: # [osx and x86_64]
        strong_constrains: # [osx and x86_64]
          - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.12") }}  # [osx and x86_64]
      # the distributed binaries are already relocatable
      binary_relocation: False
      runpath_whitelist:
        - $ORIGIN/../lib
      missing_dso_whitelist:
        - /usr/lib/libresolv.9.dylib
        - /usr/lib/libc++.1.dylib
        - /usr/lib/libc++abi.dylib
        - /usr/lib/libiconv.2.dylib
        - /usr/lib/libcurl.4.dylib
        - /usr/lib/libxar.1.dylib
        - $RPATH/libLLVM-14-rust-1.64.0-stable.so
        # Since 1.32.0 macOS also needs:
        - /System/Library/Frameworks/Python.framework/Versions/2.7/Python
        - /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
        - /usr/lib/libcompression.dylib
        - /usr/lib/libedit.3.dylib
        - /usr/lib/libform.5.4.dylib
        - /usr/lib/libncurses.5.4.dylib
        - /usr/lib/libpanel.5.4.dylib
        - /usr/lib/libxml2.2.dylib
        # Fixed via install_name_tool now (just declaring it here meant the thing using -
        # lib/rustlib/x86_64-apple-darwin/lib/python2.7/site-packages/lldb/lldb-argdumper - was
        # still unable to find it at runtime).
        # - $RPATH/libLLVM.dylib

        - '**/ld-linux-x86-64.so.2'
        - '**/libc.so.6'
        - '**/libdl.so.2'
        - '**/ld64.so.*'
        - '**/libgcc_s.so.1'
        - '**/libm.so.6'
        - '**/libpthread.so.0'
        - '**/librt.so.1'
        - '**/libgcc_s.so.1'
        - '**/libz.so.1'
        # Since 1.32.0 linux also needs:
        - '**/libstdc++.so.6'
        - '*/api-ms-win-core-winrt-l1-1-0.dll'  # [win]
    requirements:
      build:
        - {{ compiler('c') }}    # [osx]
        - posix  # [win]
    test:
      requires:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      files:
        - forge_test.sh  # [not win]
      commands:
        - if exist %LIBRARY_PREFIX%\share\doc\rust\html\sysroot exit 1  # [win]
        - rustc --version
        - cargo --help
        - rustc --help
        - rustdoc --help
        - time bash ./forge_test.sh  # [not win]

  - name: rust-gnu  # [win]
    script: install-gnu.bat  # [win]
    build:  # [win]
      # the distributed binaries are already relocatable
      binary_relocation: False  # [win]
    requirements:  # [win]
      build:  # [win]
        - posix # [win]
    test:  # [win]
      commands:  # [win]
        - rustc --version  # [win]
        - cargo --help  # [win]
        - rustc --help  # [win]
        - rustdoc --help  # [win]
        - if exist %LIBRARY_PREFIX%\share\doc\rust\html\sysroot exit 1  # [win]

  - name: rust-std-{{ rust_arch }}
    build:
      binary_relocation: False
    script: install-rust-std.sh  # [unix]
    script: install-msvc.bat  # [win]
    requirements:
      build:
        - posix  # [win]
      run:
        - {{ pin_subpackage("rust", exact=True) }}
    test:
      commands:
        - test -d $PREFIX/lib/rustlib

  - name: rust-std-{{ rust_std_extra }}
    script: install-rust-std-extra.sh  # [unix]
    script: install-msvc.bat  # [win]
    requirements:
      build:
        - posix  # [win]
      run:
        - {{ pin_subpackage("rust-std-" ~ rust_arch, exact=True) }}
    test:
      commands:
        - test -d $PREFIX/lib/rustlib/{{ rust_std_extra }}  # [unix]
        - if not exist "%LIBRARY_PREFIX%/lib/rustlib/{{ rust_std_extra }}" exit 1  # [win]
        # Make sure that the outputs do not clobber with other rust components
        - test -z "$(ls "${PREFIX}"/lib/rustlib/ | grep -v {{ rust_std_extra }})"  # [unix]
        - dir /b "%LIBRARY_PREFIX%" | findstr /v "{{ rust_std_extra }}" >nul || exit 1  # [win]

about:
  home: https://www.rust-lang.org
  license: MIT AND Apache-2.0
  license_family: OTHER
  license_url: https://github.com/rust-lang/rust/blob/{{ version }}/COPYRIGHT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
  description: |
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://github.com/rust-lang/rust
  doc_url: https://www.rust-lang.org/learn

extra:
  # The license files cannot be found properly on Windows
  skip-lints:
    - missing_license_file
  recipe-maintainers:
    - abhi18av
    - dlaehnemann
    - johanneskoester
    - pkgw
    - katietz
