# !! update of rust version should be carried out together with rust-activation version update !!
# https://github.com/AnacondaRecipes/rust-activation-feedstock
{% set name = "rust" %}
{% set version = "1.97.1" %}

package:
  name: {{ name }}-suite
  version: {{ version }}

source:
    #### start of main rust toolchain sources
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-unknown-linux-gnu.tar.gz  # [linux and x86_64]
    sha256: b4cdbc7cc6b0ee0a2666b1872769fdb2ad8393b28b63952f6493b4b400e4832b  # [linux and x86_64]
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-aarch64-unknown-linux-gnu.tar.gz  # [linux and aarch64]
    sha256: 2f2496c70bd336a66a4c8baf2d303ba161f3552f192444c3639ba903c7c1e2c5  # [linux and aarch64]
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-aarch64-apple-darwin.tar.gz  # [osx and arm64]
    sha256: cbd14c36f039f6f11f38148a6295d8234d18ddf20bea53031c86f119423a8b26  # [osx and arm64]
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-pc-windows-msvc.tar.gz  # [win and x86_64]
    sha256: efbb66ddc8ca271424e5bf4de9b5c552c2f6cc68e36309b2c7bbe683c72d0334  # [win and x86_64]
    folder: msvc  # [win and x86_64]
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-aarch64-pc-windows-msvc.tar.gz  # [win and arm64]
    sha256: 96cceaec35b69832aead092bab44d120ea88bcaf57bb3377354f1148b25c00d1  # [win and arm64]
    folder: msvc  # [win and arm64]
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-pc-windows-gnu.tar.gz  # [win and x86_64]
    sha256: 54709e21a51ae8d2702c123d42d8fcbb5495029f7a0627cec6cea560e7bbb2e5  # [win and x86_64]
    folder: gnu  # [win and x86_64]
  - url: https://static.rust-lang.org/dist/rust-{{ version }}-aarch64-pc-windows-gnullvm.tar.gz  # [win and arm64]
    sha256: 9fd5245c4293a9913c8b7c2accfaa02e48823c42bfc952fbb2659a5f39cf9c95  # [win and arm64]
    folder: gnu  # [win and arm64]
    #### end of main rust toolchain sources
    #### start of rust-std-extra toolchain sources
  - url: https://static.rust-lang.org/dist/rust-std-{{ version }}-wasm32-wasip1.tar.gz
    sha256: f7914edd8e8f50f40f4294ff58f05c0ce3dd5be2cb245658a6a4205df415cd34
    folder: rust-std-wasm32-wasip1
  - url: https://static.rust-lang.org/dist/rust-std-{{ version }}-wasm32-wasip2.tar.gz
    sha256: 67f9bbbeee9a8a015d64cc13b21dd3dcd1292a8b29562f03816ea0c81d63df25
    folder: rust-std-wasm32-wasip2
    #### end of rust-std-extra toolchain sources

build:
  number: 1

outputs:
  - name: rust
    script: install-msvc.bat  # [win]
    script: install-unix.sh  # [not win]
    build:
      # The distributed binaries are already relocatable
      binary_relocation: False
      runpath_whitelist:
        - $ORIGIN/../lib
      missing_dso_whitelist:
        - /usr/lib/libresolv.9.dylib
        - /usr/lib/libc++.1.dylib
        - /usr/lib/libc++abi.dylib
        - /usr/lib/libiconv.2.dylib
        - /usr/lib/libcurl.4.dylib
        - /usr/lib/libxar.1.dylib
        - $RPATH/libLLVM-14-rust-1.64.0-stable.so
        # Since 1.32.0 macOS also needs:
        - /System/Library/Frameworks/Python.framework/Versions/2.7/Python
        - /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
        - /usr/lib/libcompression.dylib
        - /usr/lib/libedit.3.dylib
        - /usr/lib/libform.5.4.dylib
        - /usr/lib/libncurses.5.4.dylib
        - /usr/lib/libpanel.5.4.dylib
        - /usr/lib/libxml2.2.dylib
        # Fixed via install_name_tool now (just declaring it here meant the thing using -
        # lib/rustlib/x86_64-apple-darwin/lib/python2.7/site-packages/lldb/lldb-argdumper - was
        # still unable to find it at runtime).
        # - $RPATH/libLLVM.dylib

        - '**/ld-linux-x86-64.so.2'
        - '**/libc.so.6'
        - '**/libdl.so.2'
        - '**/ld64.so.*'
        - '**/libgcc_s.so.1'
        - '**/libm.so.6'
        - '**/libpthread.so.0'
        - '**/librt.so.1'
        - '**/libgcc_s.so.1'
        - '**/libz.so.1'
        # Since 1.32.0 linux also needs:
        - '**/libstdc++.so.6'
        - '*/api-ms-win-core-winrt-l1-1-0.dll'  # [win]
        - '*/api-ms-win-core-winrt-error-l1-1-0.dll'  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}    # [osx]
        - {{ compiler('c') }}    # [osx]
    test:
      requires:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      files:
        - forge_test.sh  # [not win]
      commands:
        - if exist %LIBRARY_PREFIX%\share\doc\rust\html\sysroot exit 1  # [win]
        - rustc --version
        - cargo --help
        - rustc --help
        - rustdoc --help
        - time bash ./forge_test.sh  # [not win]

  - name: rust-gnu  # [win]
    script: install-gnu.bat  # [win]
    build:  # [win]
      # the distributed binaries are already relocatable
      binary_relocation: False  # [win]
    test:  # [win]
      commands:  # [win]
        - rustc --version  # [win]
        - cargo --help  # [win]
        - rustc --help  # [win]
        - rustdoc --help  # [win]
        - if exist %LIBRARY_PREFIX%\share\doc\rust\html\sysroot exit 1  # [win]

  - name: rust-std-{{ rust_std_extra }}
    build:
      binary_relocation: False
      runpath_whitelist:
        - $ORIGIN/../lib
      missing_dso_whitelist:
        - "/lib64/libgcc_s.so.*"
        - "/lib64/librt.so.*"
        - "/lib64/libpthread.so.*"
        - "/lib64/libdl.so.*"
        - "/lib64/libc.so.*"
        - "/lib64/ld-linux-x86-64.so.*"  # [linux and x86_64]
      run_exports:
        strong:
          - {{ pin_subpackage("rust", exact=True) }}
    script: install-rust-std-extra.sh  # [unix]
    script: install-rust-std-extra.bat  # [win]
    test:
      commands:
        - echo ON  # [win]
        - test -f $PREFIX/lib/rustlib/{{ rust_std_extra }}/lib/libcore*.rlib  # [unix]
        # Make sure that the outputs do not clobber with other rust components
        - test -f $PREFIX/lib/rustlib/{{ rust_std_extra }}/lib/self-contained/libc.a  # [unix]
        - rustc --print target-list | grep {{ rust_std_extra }}  # [unix]
      requires:
        - {{ pin_subpackage('rust', exact=True) }}  # [unix]

about:
  home: https://www.rust-lang.org
  license: MIT AND Apache-2.0
  license_family: OTHER
  license_url: https://github.com/rust-lang/rust/blob/{{ version }}/COPYRIGHT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
  description: |
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://github.com/rust-lang/rust
  doc_url: https://www.rust-lang.org/learn

extra:
  # The license files cannot be found properly on Windows
  skip-lints:
    - missing_license_file
  recipe-maintainers:
    - abhi18av
    - dlaehnemann
    - johanneskoester
    - pkgw
    - katietz
