# !! update of rust version should be carried out together with rust-activation version update !!
# https://github.com/AnacondaRecipes/rust-activation-feedstock
{% set date = "2026-04-01" %}
{% set version = "1.96.0_" ~ date.replace('-', '_') %}

package:
  name: rust-nightly-split
  version: {{ version }}

source:
    #### start of main rust toolchain sources
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-x86_64-unknown-linux-gnu.tar.gz  # [linux and x86_64]
    sha256: 23757d8f63204026b91efa333c138a764d5498af49ca8c41c817b8ddaf8136d2  # [linux and x86_64]
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-aarch64-unknown-linux-gnu.tar.gz  # [linux and aarch64]
    sha256: 6210ba08d54d229fae9cfaf83b7b812d10a0b93bd8eca25df893da32602625ef  # [linux and aarch64]
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-aarch64-apple-darwin.tar.gz  # [osx and arm64]
    sha256: e2b2e2fb9688399690a820c012a1a4d65112061634ab5737f3e2915017874bd4  # [osx and arm64]
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-x86_64-pc-windows-msvc.tar.gz  # [win]
    sha256: 590c2e94dd08f438917f0a85843417c148bfda324f2e63a05010a52d3af56629  # [win]
    folder: msvc  # [win]
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-x86_64-pc-windows-gnu.tar.gz  # [win]
    sha256: ae6b48d977bc05f2579ca45509aeb2e3a9ef09107eae4e538f63465e73578336  # [win]
    folder: gnu  # [win]
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-std-nightly-wasm32-wasip1.tar.gz
    sha256: 9ce487fd9da318a004f507cbf5af084955a3d681808252cf613c7a1310ad8138
    folder: rust-std-wasm32-wasip1
  - url: https://static.rust-lang.org/dist/{{ date }}/rust-std-nightly-wasm32-wasip2.tar.gz
    sha256: 296081ddfafab14643c9a604602d57897c3c35627718beee769e742db92f4fc7
    folder: rust-std-wasm32-wasip2
    #### end of rust-std-extra toolchain sources

build:
  number: 0

outputs:
  - name: rust-nightly
    script: install-msvc.bat  # [win]
    script: install-unix.sh  # [not win]
    build:
      # The distributed binaries are already relocatable
      binary_relocation: False
      runpath_whitelist:
        - $ORIGIN/../lib
      missing_dso_whitelist:
        - /usr/lib/libresolv.9.dylib
        - /usr/lib/libc++.1.dylib
        - /usr/lib/libc++abi.dylib
        - /usr/lib/libiconv.2.dylib
        - /usr/lib/libcurl.4.dylib
        - /usr/lib/libxar.1.dylib
        - $RPATH/libLLVM-14-rust-1.64.0-stable.so
        # Since 1.32.0 macOS also needs:
        - /System/Library/Frameworks/Python.framework/Versions/2.7/Python
        - /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
        - /usr/lib/libcompression.dylib
        - /usr/lib/libedit.3.dylib
        - /usr/lib/libform.5.4.dylib
        - /usr/lib/libncurses.5.4.dylib
        - /usr/lib/libpanel.5.4.dylib
        - /usr/lib/libxml2.2.dylib
        # Fixed via install_name_tool now (just declaring it here meant the thing using -
        # lib/rustlib/x86_64-apple-darwin/lib/python2.7/site-packages/lldb/lldb-argdumper - was
        # still unable to find it at runtime).
        # - $RPATH/libLLVM.dylib

        - '**/ld-linux-x86-64.so.2'
        - '**/libc.so.6'
        - '**/libdl.so.2'
        - '**/ld64.so.*'
        - '**/libgcc_s.so.1'
        - '**/libm.so.6'
        - '**/libpthread.so.0'
        - '**/librt.so.1'
        - '**/libgcc_s.so.1'
        - '**/libz.so.1'
        # Since 1.32.0 linux also needs:
        - '**/libstdc++.so.6'
        - '*/api-ms-win-core-winrt-l1-1-0.dll'  # [win]
        - '*/api-ms-win-core-winrt-error-l1-1-0.dll'  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}    # [osx]
        - {{ compiler('c') }}    # [osx]
        - msys2-posix  # [win]
    test:
      requires:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      files:
        - forge_test.sh  # [not win]
      commands:
        - if exist %LIBRARY_PREFIX%\share\doc\rust\html\sysroot exit 1  # [win]
        - rustc --version
        - cargo --help
        - rustc --help
        - rustdoc --help
        - time bash ./forge_test.sh  # [not win]

  - name: rust-gnu-nightly  # [win]
    script: install-gnu.bat  # [win]
    build:  # [win]
      # the distributed binaries are already relocatable
      binary_relocation: False  # [win]
      missing_dso_whitelist:  # [win]
        - '*/api-ms-win-core-winrt-l1-1-0.dll'  # [win]
        - '*/api-ms-win-core-winrt-error-l1-1-0.dll'  # [win]
    requirements:  # [win]
      build:  # [win]
        - msys2-posix # [win]
    test:  # [win]
      commands:  # [win]
        - rustc --version  # [win]
        - cargo --help  # [win]
        - rustc --help  # [win]
        - rustdoc --help  # [win]
        - if exist %LIBRARY_PREFIX%\share\doc\rust\html\sysroot exit 1  # [win]
  - name: rust-std-{{ rust_std_extra }}-nightly
    build:
      binary_relocation: False
      runpath_whitelist:
        - $ORIGIN/../lib
      missing_dso_whitelist:
        - "/lib64/libgcc_s.so.*"
        - "/lib64/librt.so.*"
        - "/lib64/libpthread.so.*"
        - "/lib64/libdl.so.*"
        - "/lib64/libc.so.*"
        - "/lib64/ld-linux-x86-64.so.*"  # [linux and x86_64]
      run_exports:
        strong:
          - {{ pin_subpackage("rust-nightly", exact=True) }}
    script: install-rust-std-extra.sh  # [unix]
    script: install-rust-std-extra.bat  # [win]
    requirements:
      build:
        - msys2-posix  # [win]
    test:
      commands:
        - echo ON  # [win]
        - test -f ${PREFIX}/lib/rustlib/{{ rust_std_extra }}/lib/libcore*.rlib  # [unix]
        # Make sure that the outputs do not clobber with other rust components
        - test -f ${PREFIX}/lib/rustlib/{{ rust_std_extra }}/lib/self-contained/libc.a  # [unix]
        - rustc --print target-list | grep {{ rust_std_extra }}  # [unix]
      requires:
        - {{ pin_subpackage('rust-nightly', exact=True) }}  # [unix]

about:
  home: https://www.rust-lang.org
  license: MIT AND Apache-2.0
  license_family: OTHER
  license_url: https://github.com/rust-lang/rust/blob/{{ version }}/COPYRIGHT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
  description: |
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://github.com/rust-lang/rust
  doc_url: https://www.rust-lang.org/learn

extra:
  # The license files cannot be found properly on Windows
  skip-lints:
    - missing_license_file
  recipe-maintainers:
    - abhi18av
    - dlaehnemann
    - johanneskoester
    - pkgw
    - katietz