{% set version = "1.32.0" %}

package:
  name: rust
  version: {{ version }}

source:
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-unknown-linux-gnu.tar.gz  # [linux]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-apple-darwin.tar.gz       # [osx]
  url: https://static.rust-lang.org/dist/rust-{{ version }}-x86_64-pc-windows-msvc.tar.gz    # [win64]
  sha256: e024698320d76b74daf0e6e71be3681a1e7923122e3ebd03673fcac3ecc23810  # [linux]
  sha256: f0dfba507192f9b5c330b5984ba71d57d434475f3d62bd44a39201e36fa76304  # [osx]
  sha256: 51b0b64cc843d6e443bf19f89b61addb532ea61e02777c7e80a185a9a263776b  # [win64]

build:
  number: 0
  # the distributed binaries are already relocatable
  binary_relocation: False
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib
    - /usr/lib/libc++.1.dylib
    - /usr/lib/libc++abi.dylib
    - /usr/lib/libiconv.2.dylib
    - /usr/lib/libcurl.4.dylib
    - /usr/lib/libxar.1.dylib
    - /lib64/ld-linux-x86-64.so.2
    - /lib64/libc.so.6
    - /lib64/libdl.so.2
    - /lib64/libgcc_s.so.1
    - /lib64/libm.so.6
    - /lib64/libpthread.so.0
    - /lib64/librt.so.1

requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}

test:
  files:
    - forge_test.sh
  commands:
    - time bash ./forge_test.sh  # [not win]
    - bash forge_test.sh  # [win]

about:
  home: https://www.rust-lang.org
  license: MIT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://doc.rust-lang.org/std/
  doc_url: https://www.rust-lang.org/en-US/documentation.html

extra:
  recipe-maintainers:
    - johanneskoester
    - abhi18av
    - pkgw
    - dlaehnemann
