{% set date = "2018-09-30" %}
{% set version = "1.30.0_" ~ date.replace('-', '_') %}

package:
  name: rust-nightly
  version: {{ version }}

source:
  # Look in https://static.rust-lang.org/dist/channel-rust-nightly.toml
  url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-x86_64-unknown-linux-gnu.tar.xz  # [linux]
  url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-x86_64-apple-darwin.tar.xz  # [osx]
  url: https://static.rust-lang.org/dist/{{ date }}/rust-nightly-x86_64-pc-windows-msvc.tar.xz  # [win64]

  sha256: 312a760de45dd0d7301e8bf7034225fbfc6ee6dbb2ddec56c9f5383a6d00ca62  # [linux]
  sha256: 0f97c4a262b4806d68d42ac121f960726e776ca519496c828133606fbe324648  # [osx]
  sha256: e368f9e0b982b3263b0a958fc6788923d594fcbc2e2494c9ef8df84436cbcbfa  # [win64]

build:
  number: 0
  # the distributed binaries are already relocatable
  binary_relocation: False
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib
    - /usr/lib/libc++.1.dylib
    - /usr/lib/libc++abi.dylib
    - /usr/lib/libiconv.2.dylib
    - /usr/lib/libcurl.4.dylib
    - /usr/lib/libxar.1.dylib
    # Needed for nightly
    - /usr/lib/libxml2.2.dylib
    - /usr/lib/libform.5.4.dylib
    - /System/Library/Frameworks/Python.framework/Versions/2.7/Python
    - /usr/lib/libedit.3.dylib
    - /usr/lib/libncurses.5.4.dylib
    - /usr/lib/libpanel.5.4.dylib
    - /usr/lib/libcompression.dylib
    - /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols

    - '**ld-linux-x86-64.so.2'
    - '**libc.so.6'
    - '**libdl.so.2'
    - '**libgcc_s.so.1'
    - '**libm.so.6'
    - '**libpthread.so.0'
    - '**librt.so.1'
    - '**libgcc_s.so.1'
    - '**libstdc++.so.6'

requirements:
  build:
    - posix  # [win]

test:
  requires:
    - gcc_impl_linux-64  # [linux]
    - clang_osx-64  # [osx]
  files:
    - forge_test.sh
  commands:
    - time bash ./forge_test.sh  # [not win]
    - bash forge_test.sh  # [win]

about:
  home: https://www.rust-lang.org
  license: MIT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://doc.rust-lang.org/std/
  doc_url: https://www.rust-lang.org/en-US/documentation.html

extra:
  recipe-maintainers:
    - johanneskoester
    - abhi18av
    - pkgw
    - dlaehnemann
